# Generated by Django 2.2 on 2019-04-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190406_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
