# Generated by Django 2.2 on 2019-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190406_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.CharField(default='link', max_length=1000),
            preserve_default=False,
        ),
    ]
